---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kind-kind-wego-nginx
  namespace: wego-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: kind-kind-wego-nginx
  url: ssh://git@github.com/wkp-example-org/nginx.git

